services:
  - type: web
    name: off-market-ai-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false 